[servidores]
server1 ansible_host=127.0.0.1 ansible_port=2201
server2 ansible_host=127.0.0.1 ansible_port=2202
server3 ansible_host=127.0.0.1 ansible_port=2203
server4 ansible_host=127.0.0.1 ansible_port=2204
server5 ansible_host=127.0.0.1 ansible_port=2205

[all:vars]
ansible_user=ansible
ansible_password=ansible
# Especificamos la clave para poder hacer sudo en Ansible si fuera necesario
ansible_become_pass=ansible
